### ISSUE TITLE
Add Selection Sort in cpp

### ISSUE THREAD

**Issue by anweshabanerjee10** [kanisht09/Data-Structures-and-Algorithms#104]

**Comment by roshan2152** [comment]
@kanisht09  can i work on this?

**Comment by ShishuSidharth** [comment]
Please assign this to me

**Comment by kanisht09** [comment]
> @kanisht09 can i work on this?

hi there you can create a new issue if you want , if i feel the issue is worthy i will assign you to that issue. This issue is already been assigned so hope you understand !
