### ISSUE TITLE
Add Tree in CPP

### ISSUE THREAD

**Issue by sahil19solanki** [kanisht09/Data-Structures-and-Algorithms#113]
impliment tree from scrach

**Comment by kanisht09** [comment]
Hi @sahil19solanki can you please provide the details about your issue. I mean to say what exactly you want to add . Is it for general n-array trees or for binary tree only. Let me know in comments.

**Comment by sahil19solanki** [comment]
hello @kanisht09 , I will add all the codes based on tree as I am leaning them currently , so if you think that  I will add value to your repo kindly assign this to me and this will be good kickstart for me to start contributing to open source ,I will start with general tree and keep adding and devide them into different folders with good explanation

**Comment by kanisht09** [comment]
@sahil19solanki don't make any spelling mistakes in the comments (if any) in the code.
