### ISSUE TITLE
Please assign me a issue.

### ISSUE THREAD

**Issue by dcod3r** [kanisht09/Data-Structures-and-Algorithms#115]
I can also add some algorim or code based on my knowledge

**Comment by kanisht09** [comment]
Hi can you please look into the repo and find some data structure which is not have been implemented or is missing.
I think map is still left so have a look at that

**Comment by dcod3r** [comment]
ok sir, i can add some problem abd implementation of maps, i.e, HashMap UorderMaps and all

**Comment by dcod3r** [comment]
And also i can add some questions related to bitwise operator in C++

**Comment by kanisht09** [comment]
yeah sure create a proper issue detailing what you want to do in description and please close this issue and add a new one.
