### ISSUE TITLE
Program to Implement Dequeue in CPP

### ISSUE THREAD

**Issue by dcod3r** [kanisht09/Data-Structures-and-Algorithms#118]

**Comment by dcod3r** [comment]
Do I have to Pull Request now?

**Comment by Sourz-101** [comment]
where do I have to implement it 
I mean in which file/directory

**Comment by dcod3r** [comment]
Excuse me, @Sourz-101 I think Owner had assigned this task to me.

**Comment by kanisht09** [comment]
> Do I have to Pull Request now?

yes you can

**Comment by dcod3r** [comment]
Done.
