### ISSUE TITLE
Singly Linked List implementation in Python

### ISSUE THREAD

**Issue by anmolojha2633** [kanisht09/Data-Structures-and-Algorithms#131]

**Comment by hardiksharma11** [comment]
I would like to work on this ..plz assign it to me

**Comment by kanisht09** [comment]
> I would like to work on this ..plz assign it to me

hi @hardiksharma11 I have assigned it to @anmolojha2633 for the time being since he was the first to raise an issue , so in case if he is unable to come up with the solution , I will assign it to you
