### ISSUE TITLE
Add Linear search 

### ISSUE THREAD

**Issue by PumpkinManiac** [kanisht09/Data-Structures-and-Algorithms#143]

**Comment by kanisht09** [comment]
@PumpkinManiac may I know where are you willing to add this algorithm. I mean in which language, can you please specify.

**Comment by PumpkinManiac** [comment]
Python

**Comment by PumpkinManiac** [comment]
@kanisht09 Python

**Comment by kanisht09** [comment]
@PumpkinManiac please start working asap
